modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="wantedmekanism"
version="${file.jarVersion}"
displayName="Wanted Mekanism"
description='''
Wanted features for some Mekanism Tool and Armor. Mainly Atomic Disassembler and Armored Jetpack
'''
[[dependencies.omnitools]]
    modId="mekanism"
    mandatory=true
    versionRange="10.1.0.455"
    ordering="AFTER"
    side="BOTH"


